In [1]:
import pandas as pd
import numpy as np 

In [2]:
columns = ['dateTime', 'sedentary', 'LPA', 'MPA', 'VPA', 'steps', 'duration_score', 'deep_sleep_in_minutes', 'resting_heart_rate', 'restlessness']

In [3]:
df1 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p01_merged.csv')
df1 = df1[columns]
print (df1.head())
df1.shape

     dateTime  sedentary  LPA  MPA  VPA  steps  duration_score  \
0  2019-11-01        636  245   58   72  17873            38.0   
1  2019-11-02        709  202   43   56  13118            37.0   
2  2019-11-03        648  262   63   45  14312            38.0   
3  2019-11-04        760  230   23   28  10970            38.0   
4  2019-11-05        737  263   22   56  16186            36.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   27.0                53.0      0.053635  
1                   36.0                53.0      0.078978  
2                   38.0                52.0      0.093491  
3                   37.0                53.0      0.064851  
4                   26.0                54.0      0.093185  


(152, 10)

In [4]:
df2 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p02_merged.csv')
df2 = df2[columns]
print (df2.shape)
print (df2.head())
df2 = df1.append(df2, ignore_index=True)
df2.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-01       1440    0    0    0    385.0            39.0   
1  2019-11-02       1440    0    0    0  17228.0            32.0   
2  2019-11-03       1440    0    0    0  16074.0            29.0   
3  2019-11-04       1440    0    0    0  17375.0            39.0   
4  2019-11-05       1424   16    0    0  18903.0            38.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   40.0                45.0      0.152147  
1                   72.0                46.0      0.201690  
2                   35.0                46.0      0.075534  
3                   76.0                48.0      0.201717  
4                   67.0                47.0      0.137809  


(304, 10)

In [5]:
df3 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p03_merged.csv')
df3 = df3[columns]
print (df3.shape)
print (df3.head())
df3 = df3.append(df2, ignore_index=True)
df3.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-01       1035  227    7   36  11204.0            35.0   
1  2019-11-02        888   91   12   25   4435.0            42.0   
2  2019-11-03       1440    0    0    0      0.0            38.0   
3  2019-11-04       1440    0    0    0   6710.0            39.0   
4  2019-11-05       1276  127   11   26   9079.0            29.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   59.0                60.0      0.087740  
1                  107.0                61.0      0.067358  
2                   67.0                59.0      0.089757  
3                   80.0                58.0      0.071429  
4                   22.0                57.0      0.057831  


(456, 10)

In [6]:
df4 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p04_merged.csv')
df4 = df4[columns]
print (df4.shape)
print (df4.head())
df4 = df4.append(df3, ignore_index=True)
df4.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-01       1440    0    0    0   9243.0            36.0   
1  2019-11-02       1440    0    0    0  10246.0            37.0   
2  2019-11-03       1440    0    0    0  11489.0            40.0   
3  2019-11-04       1440    0    0    0   7587.0            44.0   
4  2019-11-05       1390    0    0   50   4954.0            40.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                  105.0                67.0      0.105209  
1                   91.0                66.0      0.109902  
2                  139.0                65.0      0.103800  
3                  108.0                66.0      0.108354  
4                   97.0                66.0      0.077833  


(608, 10)

In [7]:
df5 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p05_merged.csv')
df5 = df5[columns]
print (df5.shape)
print (df5.head())
df5 = df5.append(df4, ignore_index=True)
df5.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-01        556  318   40   38  14306.0            42.0   
1  2019-11-02        775  298   17   25  13349.0            34.0   
2  2019-11-03        767  267   12   34   9037.0            25.0   
3  2019-11-04       1103  255   34   48  13240.0            34.0   
4  2019-11-05       1042  301   53   44  14898.0            34.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   83.0                63.0      0.090815  
1                   71.0                64.0      0.056836  
2                   51.0                66.0      0.114120  
3                   78.0                66.0      0.076716  
4                   88.0                66.0      0.082749  


(760, 10)

In [8]:
df6 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p06_merged.csv')
df6 = df6[columns]
print (df6.shape)
print (df6.head())
df6 = df6.append(df5, ignore_index=True)
df6.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA  steps  duration_score  \
0  2019-11-01       1422   18    0    0    411            35.0   
1  2019-11-02        544  245   27   94  21036            39.0   
2  2019-11-03        820  204   24   29   5840            40.0   
3  2019-11-04        605  319   26   61  16483            43.0   
4  2019-11-05        502  280   89  146  22329            39.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   65.0                47.0      0.067133  
1                   76.0                49.0      0.057176  
2                   48.0                50.0      0.041766  
3                   61.0                50.0      0.035320  
4                  113.0                49.0      0.042998  


(912, 10)

In [9]:
df7 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p07_merged.csv')
df7 = df7[columns]
print (df7.shape)
print (df7.head())
df7 = df7.append(df6, ignore_index=True)
df7.shape

(148, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-05       1440    0    0    0   9370.0            40.0   
1  2019-11-06       1270   82   23   65  19979.0            37.0   
2  2019-11-07        563  226   21  105   9614.0            41.0   
3  2019-11-08        660  224    9   29  28445.0            41.0   
4  2019-11-09        383  243   16  324   6203.0            39.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                  104.0                55.0      0.054002  
1                   74.0                53.0      0.052500  
2                   96.0                53.0      0.042448  
3                   95.0                52.0      0.054081  
4                   71.0                52.0      0.062681  


(1060, 10)

In [10]:
df8 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p08_merged.csv')
df8 = df8[columns]
print (df8.shape)
print (df8.head())
df8 = df8.append(df7, ignore_index=True)
df8.shape

(143, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-10       1440    0    0    0  14174.0            37.0   
1  2019-11-11       1191  159    9   81  24821.0            42.0   
2  2019-11-12        566  209   21  159  11012.0            37.0   
3  2019-11-13        647  269   10   30  19199.0            40.0   
4  2019-11-14        635  199   44   96  13145.0            42.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   62.0                52.0      0.107628  
1                   72.0                51.0      0.072572  
2                   56.0                53.0      0.082529  
3                   70.0                51.0      0.082699  
4                   62.0                53.0      0.102337  


(1203, 10)

In [11]:
df9 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p09_merged.csv')
df9 = df9[columns]
print (df9.shape)
print (df9.head())
df9 = df9.append(df8, ignore_index=True)
df9.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA   steps  duration_score  \
0  2019-11-01        931  121    0    0  4014.0             3.0   
1  2019-11-02       1372   68    0    0  2775.0            35.0   
2  2019-11-03        746  219   14   31  9663.0            27.0   
3  2019-11-04        874  199    0    0  6140.0            37.0   
4  2019-11-05        834  163    4    6  5704.0            42.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   66.0                59.0      0.110968  
1                   92.0                60.0      0.076561  
2                   70.0                61.0      0.073469  
3                   69.0                60.0      0.065882  
4                   86.0                59.0      0.073488  


(1355, 10)

In [12]:
df10 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p10_merged.csv')
df10 = df10[columns]
print (df10.shape)
print (df10.head())
df10 = df10.append(df9, ignore_index=True)
df10.shape

(148, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-05       1440    0    0    0   9198.0            42.0   
1  2019-11-06       1440    0    0    0   9865.0            38.0   
2  2019-11-07       1309   30   39   62  13397.0            39.0   
3  2019-11-08        549  313    0    0  15800.0            41.0   
4  2019-11-09        617  232   24   52  13096.0            39.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   50.0                71.0      0.146390  
1                   75.0                70.0      0.123288  
2                   59.0                65.0      0.120674  
3                   82.0                65.0      0.115226  
4                   53.0                65.0      0.121547  


(1503, 10)

In [13]:
df11 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p11_merged.csv')
df11 = df11[columns]
print (df11.shape)
print (df11.head())
df11 = df11.append(df10, ignore_index=True)
df11.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-01       1440    0    0    0      0.0            45.0   
1  2019-11-02       1440    0    0    0      0.0            32.0   
2  2019-11-03       1440    0    0    0  21596.0            35.0   
3  2019-11-04       1440    0    0    0  11560.0            36.0   
4  2019-11-05       1440    0    0    0   2609.0            38.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                  110.0                60.0      0.073105  
1                   76.0                64.0      0.079699  
2                   77.0                69.0      0.080925  
3                   89.0                66.0      0.079038  
4                   66.0                65.0      0.073054  


(1655, 10)

In [14]:
df13 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p13_merged.csv')
df13 = df13[columns]
print (df13.shape)
print (df13.head())
df13 = df13.append(df11, ignore_index=True)
df13.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-01       1440    0    0    0  15051.0            42.0   
1  2019-11-02       1440    0    0    0  15896.0            35.0   
2  2019-11-03       1440    0    0    0   7230.0            39.0   
3  2019-11-04       1440    0    0    0   9631.0            38.0   
4  2019-11-05       1440    0    0    0  14562.0            35.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   95.0                57.0      0.076229  
1                   83.0                55.0      0.139037  
2                   92.0                58.0      0.127505  
3                   98.0                59.0      0.081146  
4                   71.0                58.0      0.095471  


(1807, 10)

In [15]:
df14 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p14_merged.csv')
df14 = df14[columns]
print (df14.shape)
print (df14.head())
df14 = df14.append(df13, ignore_index=True)
df14.shape

(140, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-13       1440    0    0    0   8725.0            35.0   
1  2019-11-14       1266  133   23   18  16612.0            41.0   
2  2019-11-15        629  234   37   77   6010.0            45.0   
3  2019-11-16        373  173   13   10   8845.0            35.0   
4  2019-11-17        660  168    9   39  10527.0            32.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   93.0                62.0      0.069490  
1                  108.0                66.0      0.138334  
2                   99.0                66.0      0.097431  
3                   83.0                64.0      0.085896  
4                   39.0                62.0      0.112169  


(1947, 10)

In [16]:
df15 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p15_merged.csv')
df15 = df15[columns]
print (df15.shape)
print (df15.head())
df15 = df15.append(df14, ignore_index=True)
df15.shape

(145, 10)
     dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0  2019-11-08       1440    0    0    0   5186.0            46.0   
1  2019-11-09       1261  159   13    7  15235.0            42.0   
2  2019-11-10        481  237   42  125  13430.0            40.0   
3  2019-11-11        612  229   20   50  19036.0            38.0   
4  2019-11-12        661  201   16   99  15421.0            39.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                   64.0                58.0      0.056706  
1                   78.0                57.0      0.062863  
2                   45.0                57.0      0.054983  
3                   60.0                56.0      0.067568  
4                   39.0                56.0      0.075774  


(2092, 10)

In [17]:
df16 = pd.read_csv(r'C:\Users\AyanC\OneDrive - Universitetet i Agder\Kalman\p16_merged.csv')
df16 = df16[columns]
print (df16.shape)
print (df16.head())
df16 = df16.append(df15, ignore_index=True)
df16.shape

(152, 10)
     dateTime  sedentary  LPA  MPA  VPA  steps  duration_score  \
0  2019-11-01        907  107    0    0   3062            38.0   
1  2019-11-02        874   94    0    0   1472            38.0   
2  2019-11-03        990   59    0    0    610            34.0   
3  2019-11-04        740   80    8    4   2177            45.0   
4  2019-11-05        816   67    0    0   1690            45.0   

   deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                  103.0                63.0      0.078853  
1                   75.0                65.0      0.099448  
2                   75.0                66.0      0.134100  
3                   99.0                67.0      0.125833  
4                  123.0                66.0      0.122870  


(2244, 10)

In [18]:
df = df16
df['sleep_duration'] = 1440 - (df['VPA'] + df['MPA'] + df['LPA'] + df['sedentary'])
df.to_csv('pmdata_merged_15.csv')

In [19]:
df

dateTime  sedentary  LPA  MPA  VPA    steps  duration_score  \
0     2019-11-01        907  107    0    0   3062.0            38.0   
1     2019-11-02        874   94    0    0   1472.0            38.0   
2     2019-11-03        990   59    0    0    610.0            34.0   
3     2019-11-04        740   80    8    4   2177.0            45.0   
4     2019-11-05        816   67    0    0   1690.0            45.0   
...          ...        ...  ...  ...  ...      ...             ...   
2239  2020-03-27        680  171   12   91  15137.0             0.0   
2240  2020-03-28        609  237   42  109      0.0             0.0   
2241  2020-03-29        983   77   11  115      0.0             0.0   
2242  2020-03-30        784   96   20  152      0.0             0.0   
2243  2020-03-31        663  135   29  117      0.0             0.0   

      deep_sleep_in_minutes  resting_heart_rate  restlessness  sleep_duration  
0                     103.0                63.0      0.078853             426  
1                      75.0                65.0      0.099448             472  
2                      75.0                66.0      0.134100             391  
3                      99.0                67.0      0.125833             608  
4                     123.0                66.0      0.122870             557  
...                     ...                 ...           ...             ...  
2239                    0.0                 0.0      0.000000             486  
2240                    0.0                 0.0      0.000000             443  
2241                    0.0                 0.0      0.000000             254  
2242                    0.0                 0.0      0.000000             388  
2243                    0.0                 0.0      0.000000             496  

[2244 rows x 11 columns]

In [20]:
columns = ['sedentary', 'LPA', 'MPA', 'VPA', 'steps', 'duration_score', 'deep_sleep_in_minutes', 'resting_heart_rate', 'restlessness']
df = df [columns]
df

sedentary  LPA  MPA  VPA    steps  duration_score  \
0           907  107    0    0   3062.0            38.0   
1           874   94    0    0   1472.0            38.0   
2           990   59    0    0    610.0            34.0   
3           740   80    8    4   2177.0            45.0   
4           816   67    0    0   1690.0            45.0   
...         ...  ...  ...  ...      ...             ...   
2239        680  171   12   91  15137.0             0.0   
2240        609  237   42  109      0.0             0.0   
2241        983   77   11  115      0.0             0.0   
2242        784   96   20  152      0.0             0.0   
2243        663  135   29  117      0.0             0.0   

      deep_sleep_in_minutes  resting_heart_rate  restlessness  
0                     103.0                63.0      0.078853  
1                      75.0                65.0      0.099448  
2                      75.0                66.0      0.134100  
3                      99.0                67.0      0.125833  
4                     123.0                66.0      0.122870  
...                     ...                 ...           ...  
2239                    0.0                 0.0      0.000000  
2240                    0.0                 0.0      0.000000  
2241                    0.0                 0.0      0.000000  
2242                    0.0                 0.0      0.000000  
2243                    0.0                 0.0      0.000000  

[2244 rows x 9 columns]

In [21]:
#df.plot.bar(colormap="Greens")

In [22]:
import matplotlib.pyplot as plt

corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [23]:
columns = ['sedentary', 'LPA', 'MPA', 'VPA', 'steps']
df = df [columns]

corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [24]:
df.shape

(2244, 5)

In [29]:
def calculate_lebel(df):
    if ((df['steps'] < 5000) and ((df['VPA']*2 + df['MPA'])*7 < 90) and (df['LPA'] >=0)): #sedentary
        return 0
    elif ((df['steps'] >= 5000) and ((df['VPA']*2 + df['MPA'])*7 >= 90) and (df['VPA']*2 + df['MPA'])*7 < 210) or (df['steps'] >= 5000 and df['steps'] <= 7499): #LPA
        return 1
    elif ((df['steps'] >= 5000) and ((df['VPA']*2 + df['MPA'])*7 >= 210) and (df['VPA']*2 + df['MPA'])*7 < 300) or (df['steps'] >= 7500 and df['steps'] <= 9999): #MPA
        return 2
    elif ((df['steps'] >= 5000) and ((df['VPA']*2 + df['MPA'])*7 >= 300) and (df['VPA']*2 + df['MPA'])*7 < 360) or (df['steps'] >= 10000 and df['steps'] <= 12499): #MPA
        return 3
    elif ((df['steps'] >= 5000) and (df['VPA']*2 + df['MPA'])*7 >= 360) or (df['steps'] >= 12500): #VPA
        return 4
    elif (df['steps'] < 5000):
        return 0

df['active'] = df.apply(calculate_lebel, axis=1)
df

c:\users\ayanc\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app


sedentary  LPA  MPA  VPA    steps  active
0           907  107    0    0   3062.0       0
1           874   94    0    0   1472.0       0
2           990   59    0    0    610.0       0
3           740   80    8    4   2177.0       0
4           816   67    0    0   1690.0       0
...         ...  ...  ...  ...      ...     ...
2239        680  171   12   91  15137.0       4
2240        609  237   42  109      0.0       0
2241        983   77   11  115      0.0       0
2242        784   96   20  152      0.0       0
2243        663  135   29  117      0.0       0

[2244 rows x 6 columns]

In [30]:
df['active'].isnull().values.any()

False

In [31]:
df.shape

(2244, 6)

In [32]:
df.to_csv('pmdata_processed_15.csv')

In [33]:
array = df.values
X = array[:,0:5]
Y = array[:,5]

In [34]:
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

test = SelectKBest(score_func=chi2, k=5)
fit = test.fit(X,Y)

set_printoptions(precision=2)
print(fit.scores_)
featured_data = fit.transform(X)
print ("\nFeatured data:\n", featured_data[0:5])

[  46983.43   35055.79    8826.42   28285.61 8557233.71]

Featured data:
 [[ 907.  107.    0.    0. 3062.]
 [ 874.   94.    0.    0. 1472.]
 [ 990.   59.    0.    0.  610.]
 [ 740.   80.    8.    4. 2177.]
 [ 816.   67.    0.    0. 1690.]]


In [35]:
from sklearn.decomposition import PCA

pca = PCA(n_components=5)
fit = pca.fit(X)
print(("Explained Variance: %s") % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [9.98e-01 1.54e-03 1.20e-04 2.94e-05 6.94e-06]
[[-1.77e-02  7.36e-03  1.16e-03  3.10e-03  1.00e+00]
 [ 9.62e-01 -2.66e-01 -3.02e-02 -4.86e-02  1.92e-02]
 [ 2.53e-01  9.47e-01  3.84e-02 -1.94e-01 -1.94e-03]
 [ 9.95e-02  1.59e-01  2.41e-01  9.52e-01 -2.64e-03]
 [-4.77e-03 -8.53e-02  9.69e-01 -2.31e-01  1.30e-04]]


In [36]:
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier()
model.fit(X, Y)
print(model.feature_importances_)

[0.08 0.09 0.07 0.12 0.64]
